version: '3'

tasks:
  default:
    deps: ["build"]
  install:
    deps: ["build"]
    cmds:
      - cp -v ./gos ~/go/bin/
      - cp -v ./gosc ~/go/bin/
  run:
    deps: ["dev"]
    cmds:
      - go run cmd/gos/main.go
  build:
    deps: ["buildgos", "buildgosc"]
  buildgos:
    cmds:
      - go build -o gos cmd/gos/main.go
  buildgosc:
    cmds:
      - go build -o gosc cmd/gosc/main.go
  dev:
    deps: ["test", "vet", "lint"]
    cmds:
      - go build -race -o gos cmd/gos/main.go
      - go build -race -o gosc cmd/gosc/main.go
  test:
    cmds:
      - go clean -testcache
      - go test -v ./... 
  fuzz:
    cmds:
      - go clean -testcache
      - go test ./internal/entry/ -fuzz=FuzzExtractURLs -fuzztime=10s
  vet:
    cmds:
      - go vet ./...
  lint:
    cmds:
      - golangci-lint run
  dev-install:
    cmds:
      - go install golang.org/x/tools/gopls@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
