version: '3'

tasks:
  default:
    deps: ["build"]
  install:
    deps: ["build"]
    cmds:
      - cp -v ./gos ~/go/bin/
  run:
    deps: ["dev"]
    cmds:
      - go run cmd/gos/main.go
    env:
      GOS_EDITOR: hx
  build:
    cmds:
      - go build -o gos cmd/gos/main.go
  dev:
    deps: ["test", "vet", "lint"]
    cmds:
      - go build -race -o gos cmd/gos/main.go
  test:
    cmds:
      - go clean -testcache
      - go test -v ./... 
  vet:
    cmds:
      - go vet ./...
  lint:
    cmds:
      - golangci-lint run
  lint-install:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
